// 389. Find the Difference

// Problem statement:

// Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then adding one more letter at a random position. Return the letter that was added to t.

// Understand the problem first:

// hme do strings s and t consist of only lowercase letters. jo t generated hy wo bna by s se randomly shuffling kr k or ek letter add kr k. hme wo letter return krna hy jo add hua hy t me.

// Approach and Solution:

// hme ye problem hash map ya frequency array se solve kr skte hy. hum dono strings ke characters ki frequency count krenge or phir dekhenge konsa character t me zyada hy jo s me nhi hy. wohi added character hoga.


var findTheDifference = function (s, t) {
    let freqMap = {};
    let result = "";

    for (let char of s) {
        if (!freqMap[char]) {
            freqMap[char] = 1;
        } else {
            freqMap[char] += 1;
        }
    }

    for (let char of t) {
        if (freqMap[char] > 0) {
            freqMap[char] -= 1;
        } else if (freqMap[char] !== char) {
            result += char;
        }
    }

    return result;
};

console.log(findTheDifference("abcd", "abcde")); // Output: "e"
